---
- name: ensure /etc/hosts is up to date 
  hosts: all
  remote_user: automation
  become: yes

  tasks:
    - name: server.example.com in /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: '192.0.2.42 server.example.com server'
        state: present

    - name: Alternatively with jinja2 templates
      template:
        src: templates/hosts.j2
        dest: /etc/hosts