---
- hosts: all 
  tasks:
  - name: Make sure chronyd is installed 
    ansible.builtin.yum:
     name: chrony
     state: latest
     update_cache: yes 

  - name: Deploy chrony.conf template 
    ansible.builtin.template:
     src: /some/full/path/chrony.conf.j2
     dest: /etc/chrony.conf
     owner: root
     group: root 
     mode: 0644 
     backup: yes 

  - name: Restart chronyd 
    ansible.builtin.service:
      name: chronyd 
      state: restarted

# cat /etc/chrony.conf 