---
- name: playbook for configuring second interface
  hosts: server1.example.com
  vars:
     target_mac: “52:54:00:fe:2f:b8”
     network_connection:
          -  name: static-network
             type: ethernet
             mac: “{{ target_mac }}”
             state: up
             ip :
               dhcp: no
               address:
                    -  192.168.0.5/24
  roles:
   -    rhel-system-roles.network

  tasks:
    - name: start the service
      service:
        name: NetworkManager
        state: started
        enabled: true

# target_mac - This is the MAC address of the second ethernet interface. 
# This will help to find out the correct interface on a managed node.

# network_connection - This variable contains information for new connections:

# name: name of the new connection
# type: new connection type
# mac: the target_mac variable
# state: activate the connection by using the up option
# ip: disable the DHCP option and assign an IP address using this parameter