---
- hosts: all
  tasks:
  # to be able to manage the file /etc/resolv.conf with Ansible, I first had to stop the NetworkManager from doing so.
    - name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
      notify:
        - reload NetworkManager
      community.general.ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        state: present
        no_extra_spaces: true
        section: main
        option: dns
        value: none
        owner: root
        group: root
        mode: 420
        backup: true

    - name: deploy resolv.conf template
      notify:
        - reload NetworkManager
      ansible.builtin.template:
        src: roles/resolv.conf/templates/resolv.conf.j2
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: 420
        backup: true

    - name: reload NetworkManager
      ansible.builtin.service:
        name: NetworkManager
        state: reloaded
